#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Соединённость

# Short bio or description (displayed in the header)
description: "научим достигать целей<br/>быстро и&nbsp;с&nbsp;удовольствием"

# Slogan (displayed in the footer)
slogan: Лёгкий способ создавать грандиозные результаты

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://avatars2.githubusercontent.com/u/12038933?v=3&s=200

image: "http://soedinennost.com/images/og-image.jpg"

keywords: "личная эффективность, достижение целей, тренинг, коучинг, результативность, продуктивность, Николай Воробьев, клуб Николая Воробьева, клуб личностного роста Николая Воробьева"
author: Николай Воробьёв

#
# Flags below are optional
#

timezone: 'MSK'

navigation:
- text: Курсы и тренинги
  url: /products/
- text: Полезные материалы
  url: /blog/
- text: Отзывы и кейсы
  url: /ok/
#- text: Партнёрка
#  url: /partner/
- text: О проекте
  url: /about/

collections:
  quests:
    output: true
    permalink: /quests/:path/
  klr:
    output: true
    permalink: /klr/:path/
  klr-weekly:
    output: true
    permalink: /klr-weekly/:path/
  cats:
    output: true
    permalink: /cats/:path/

defaults:
  - scope:
      path: ""
      type: quests
    values:
      layout: page
  - scope:
      path: ""
      type: klr
    values:
      layout: klr
  - scope:
      path: ""
      type: klr-weekly
    values:
      layout: klr-weekly-landing
  - scope:
      path: ""
      type: cats
    values:
      layout: cat

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: soedinennost

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-46456269-8

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: http://soedinennost.com

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

markdown: kramdown
permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.1.0

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem

# Exclude these files from your production _site
exclude:
  - node_modules
  - package.json
  - README.md
  - gulpfile.js
  - fast.html

# Какой проект yo содержит шоты для этого фронтенда
yo: prorealnost

vk_app_id: 5037595 # soedinennost.com
# vk_app_id: 2383340 # localhost
fb_app_id: 196110064064378 # soedinennost.com
# fb_app_id: 645740925469436 # localhost
